---
- name: Include Debian/Ubuntu specific tasks
  ansible.builtin.include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- name: Include RedHat/CentOS specific tasks
  ansible.builtin.include_tasks: setup-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Create WordPress installation directory
  ansible.builtin.file:
    path: "{{ wp_install_path }}" # /var/www/html/wordpress.local
    state: directory
    owner: "{{ 'www-data' if ansible_os_family == 'Debian' else 'apache' }}"
    group: "{{ 'www-data' if ansible_os_family == 'Debian' else 'apache' }}"
    mode: "0755"
  become: true

- name: Download WordPress
  ansible.builtin.get_url:
    url: "https://wordpress.org/wordpress-{{ wp_version }}.tar.gz"
    dest: "/tmp/wordpress-{{ wp_version }}.tar.gz"
    checksum: "{{ wp_checksum_sha256 }}"
    mode: "0644"
  become: true

- name: Extract WordPress-{{ wp_version }}.tar.gz
  ansible.builtin.unarchive:
    src: "/tmp/wordpress-{{ wp_version }}.tar.gz"
    dest: "{{ wp_install_path }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
    owner: "{{ 'www-data' if ansible_os_family == 'Debian' else 'apache' }}"
    group: "{{ 'www-data' if ansible_os_family == 'Debian' else 'apache' }}"
  become: true

- name: Delete unused directories and files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ wp_base_path }}/wordpress-{{ wp_version }}.tar.gz"

- name: Create wp-config.php from template wp-config.php.j2
  ansible.builtin.template:
    src: wp-config.php.j2
    dest: "{{ wp_install_path }}/wp-config.php"
    owner: "{{ 'www-data' if ansible_os_family == 'Debian' else 'apache' }}"
    group: "{{ 'www-data' if ansible_os_family == 'Debian' else 'apache' }}"
    mode: "0644"
  become: true
  when: wordpress_db_name is defined and wordpress_db_name != ''

- name: Create Apache Virtual Host config for WordPress from template virtualhost.conf.j2
  ansible.builtin.template:
    src: virtualhost.conf.j2
    dest: "{{ apache_conf_path_debian if ansible_os_family == 'Debian' else apache_conf_path_redhat }}/wordpress.conf"
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: Restart Apache

- name: Ensure WordPress Virtual Host symlink is enabled
  ansible.builtin.file:
    src: /etc/apache2/sites-available/wordpress.conf
    dest: /etc/apache2/sites-enabled/wordpress.conf
    state: link
  become: true
  when: ansible_os_family == 'Debian'
  notify: Restart Apache

- name: Ensure default Apache Virtual Host symlink is absent
  ansible.builtin.file:
    dest: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  become: true
  when: ansible_os_family == 'Debian'
  notify: Restart Apache

- name: Enable Apache rewrite module
  ansible.builtin.apache2_module:
    state: present
    name: rewrite
  become: true
  when: ansible_os_family == 'Debian'
  notify: Restart Apache

- name: Enable Apache rewrite module (RedHat family)
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf.modules.d/00-base.conf
    regexp: '^(#\s*)?(LoadModule\s+rewrite_module\s+modules/mod_rewrite.so)'
    line: '\2'
    backrefs: yes
  become: true
  when: ansible_os_family == 'RedHat'
  notify: Restart Apache

- name: Ensure correct ownership and permissions for the entire web root
  ansible.builtin.file:
    path: "{{ wp_install_path }}"
    state: directory
    recurse: yes
    owner: "{{ 'www-data' if ansible_os_family == 'Debian' else 'apache' }}"
    group: "{{ 'www-data' if ansible_os_family == 'Debian' else 'apache' }}"
  become: true
