---
- name: Install httpd and PHP packages on RedHat family
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ [web_pkg_redhat, php_pkgs_redhat] | flatten }}"

- name: Ensure /run/php-fpm directory exists with correct permissions
  ansible.builtin.file:
    path: /run/php-fpm/
    state: directory
    owner: apache
    group: apache
    mode: "0755"

- name: Start PHP-FPM service
  ansible.builtin.command: /usr/sbin/php-fpm
  args:
    creates: /run/php-fpm/www.sock

- name: Open HTTP and HTTPS ports in firewalld
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - http
    - https

- name: Allow Apache to connect to database (SELinux)
  ansible.posix.seboolean:
    name: httpd_can_network_connect_db
    state: true
    persistent: true
  when: ansible_selinux.status == 'enabled'

- name: Ensure /var/run/httpd exists
  ansible.builtin.file:
    path: /var/run/httpd
    state: directory
    mode: "0755"

- name: Stop httpd if running
  ansible.builtin.shell: "killall httpd || true"
  changed_when: false
