---
- name: Converge
  hosts: all
  gather_facts: true

  tasks:
    - name: "Include and run the role"
      ansible.builtin.import_role:
        name: "../../../{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"

    - name: Check uname
      ansible.builtin.raw: uname -a
      register: result
      changed_when: false
