---
name: Ansible Role Test with Molecule

on:
  push:
    branches:
      - main
    paths:
      - "defaults/**"
      - "handlers/**"
      - "meta/**"
      - "molecule/**"
      - "tasks/**"
      - "templates/**"
      - "ansible.cfg"
      - "requirements.yml"
      - "!LICENSE"
      - "!*.md"

  pull_request:
    branches:
      - main
    paths:
      - "defaults/**"
      - "handlers/**"
      - "meta/**"
      - "molecule/**"
      - "tasks/**"
      - "templates/**"
      - "ansible.cfg"
      - "requirements.yml"
      - "!LICENSE"
      - "!*.md"

jobs:
  lint:
    name: Lint Ansible Role
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install ansible-lint
        run: |
          pip install --upgrade pip
          pip install ansible-lint

      - name: Run ansible-lint
        run: |
          echo "Running ansible-lint..."
          ansible-lint .

  test:
    name: Molecule Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro_label:
          - "Ubuntu Webserver"
          - "Rocky Webserver"

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Check Docker daemon status
        run: docker info > /dev/null 2>&1 || { echo "Docker daemon is not running!"; exit 1; }

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install test dependencies.
        run: |
          pip install --upgrade pip
          pip install ansible-core==2.15.5
          pip install molecule 'molecule-plugins[docker]'

      - name: Run Molecule tests.
        run: molecule test
