name: Publicar role a Ansible Galaxy
on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Ansible Core
        run: pip install ansible-core

      - name: Run Ansible Galaxy Publisher Action
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
          $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
